export const Messages = {
    SERVER_ERROR: "Internel server error",
    USER_EXIST: "User already exist",
    OTP_RESENT: "OTP has been resent successfully",
    INVALID_NAME: "Please enter a valid name (A - Z)",
    INVALID_EMAIL: "Please enter a valid email",
    PASSWORD_LENGTH: "Your password must be at least 8 characters long",
    OTP_EXPIRED: "Your OTP has been expired, try again",
    INCORRECT_OTP: "The OTP you provided is incorrect",
    OTP_VERIFIED: "OTP verification successful",
    USER_NOT_FOUND: "User not found, try to signup",
    PASSWORD_INCORRECT: "Incorrect password, try again",
    USER_BLOCKED: "Your are blocked from Skillora",
    NO_ACCESS: "Unauthorized Access",
    USE_SOCIAL: "Your account is created using social account",
    BLOCKED: "User blocked successfully",
    UNBLOCKED: "User unblocked successfully",
    INVALID_BIO: "Bio should contains 100 - 600 characters",
    INVALID_FILE_TYPE: "Only jpeg, jpg, webp and png files allowed",
}